services:
  poop2jb:
    build:
      context: .
    image: poop2jb:local
    restart: unless-stopped
    network_mode: host
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
